import chalk from 'chalk';
import ora from 'ora';
import { formatBytes } from '../analyzers/size.js';

const BASE_URL = 'https://vibe-check.vercel.app';

/**
 * Generates a shareable URL with all report data encoded in the hash.
 * Format: https://vibe-check.vercel.app/#u=<url>&v=<vibeId>&s=<scores>&t=<stats>&r=<roastIndex>
 */
export function generateShareUrl({ url, verdict, analyses, roastIndex }) {
  // Strip protocol from URL
  const cleanUrl = url.replace(/^https?:\/\//, '');

  // Trait scores in fixed order: speed, consistency, size, honesty, headers
  const scores = [
    analyses.speed.score,
    analyses.consistency.score,
    analyses.size.score,
    analyses.honesty.score,
    analyses.headers.score,
  ].join(',');

  // Stats: avg, p50, p95, payload size in bytes
  const stats = [
    analyses.speed.stats.avg,
    analyses.speed.stats.p50,
    analyses.speed.stats.p95,
    analyses.size.stats.avgSize,
  ].join(',');

  // Encode URL component to handle special chars but keep it readable
  const encodedUrl = encodeURIComponent(cleanUrl);

  return `${BASE_URL}/#u=${encodedUrl}&v=${verdict.vibeId}&s=${scores}&t=${stats}&r=${roastIndex}`;
}

/**
 * Share a vibe-check report as a GitHub Gist (triggered by --gist flag).
 */
export async function shareToGist(report) {
  const markdown = generateMarkdownReport(report);

  const spinner = ora({
    text: chalk.dim('  Creating shareable Gist...'),
    spinner: 'dots12',
    color: 'cyan',
  }).start();

  try {
    const { execSync } = await import('node:child_process');

    // Check if gh is available
    try {
      execSync('gh --version', { stdio: 'pipe' });
    } catch {
      spinner.fail(chalk.dim('  GitHub CLI (gh) not found'));
      console.log('');
      console.log(chalk.dim('  To share via Gist, install GitHub CLI:'));
      console.log(chalk.cyan('  https://cli.github.com'));
      console.log('');
      return;
    }

    // Create the gist using gh CLI
    const filename = `vibe-check-${sanitizeUrl(report.url)}-${Date.now()}.md`;

    const fs = await import('node:fs');
    const path = await import('node:path');
    const os = await import('node:os');

    const tmpFile = path.join(os.tmpdir(), filename);
    fs.writeFileSync(tmpFile, markdown);

    const result = execSync(`gh gist create "${tmpFile}" --public -d "vibe-check report for ${report.url}"`, {
      encoding: 'utf-8',
      timeout: 15000,
    }).trim();

    try { fs.unlinkSync(tmpFile); } catch {}

    spinner.succeed(chalk.dim('  Gist created!'));
    console.log('');
    console.log(`  ${chalk.bold('Gist →')} ${chalk.cyan.underline(result)}`);
    console.log('');

  } catch (error) {
    spinner.fail(chalk.dim('  Failed to create Gist'));
    console.log(chalk.dim(`  Error: ${error.message}`));
    console.log('');
  }
}

function generateMarkdownReport(report) {
  const { url, analyses, verdict, roast, requestCount, timestamp } = report;

  const traitRows = verdict.traits
    .map(t => `| ${t.emoji} ${capitalize(t.name)} | ${renderTextBar(t.score)} | ${t.score}/100 | ${t.label} |`)
    .join('\n');

  const speedStats = analyses.speed.stats;
  const sizeStats = analyses.size.stats;
  const statusCodes = Object.entries(analyses.honesty.stats.statusCodes || {})
    .map(([code, count]) => `${code} (×${count})`)
    .join(', ');

  return `# 🔮 vibe-check report

**Target:** \`${url}\`
**Requests:** ${requestCount} · **Date:** ${new Date(timestamp).toLocaleString()}

---

## ${verdict.emoji} Verdict: **${verdict.label}** — ${verdict.overallScore}/100

> *"${roast}"*

${verdict.tagline}

---

## Trait Breakdown

| Trait | Bar | Score | Label |
|-------|-----|-------|-------|
${traitRows}

---

## Quick Stats

| Metric | Value |
|--------|-------|
| Avg Response Time | ${speedStats.avg}ms |
| P50 | ${speedStats.p50}ms |
| P95 | ${speedStats.p95}ms |
| Avg Payload Size | ${formatBytes(sizeStats.avgSize)} |
| Compressed | ${sizeStats.compressed ? '✓ Yes' : '✗ No'} |
| Status Codes | ${statusCodes} |

---

${report.shareUrl ? `🔗 **[View interactive report](${report.shareUrl})**\n\n---\n\n` : ''}
<sub>Generated by [vibe-check](https://github.com/ran4om/vibe-check) — Give any API a personality report</sub>
`;
}

function renderTextBar(score) {
  const filled = Math.round((score / 100) * 10);
  const empty = 10 - filled;
  return '█'.repeat(filled) + '░'.repeat(empty);
}

function capitalize(str) {
  return str.charAt(0).toUpperCase() + str.slice(1);
}

function sanitizeUrl(url) {
  return url
    .replace(/https?:\/\//, '')
    .replace(/[^a-zA-Z0-9]/g, '-')
    .replace(/-+/g, '-')
    .slice(0, 40);
}
