import chalk from 'chalk';
import ora from 'ora';
import { formatBytes } from '../analyzers/size.js';

/**
 * Share a vibe-check report as a GitHub Gist.
 * Uses the GitHub CLI (gh) if available, otherwise provides instructions.
 */
export async function shareToGist(report) {
  const markdown = generateMarkdownReport(report);

  const spinner = ora({
    text: chalk.dim('  Creating shareable Gist...'),
    spinner: 'dots12',
    color: 'cyan',
  }).start();

  try {
    // Try using GitHub CLI
    const { execSync } = await import('node:child_process');

    // Check if gh is available
    try {
      execSync('gh --version', { stdio: 'pipe' });
    } catch {
      spinner.fail(chalk.dim('  GitHub CLI (gh) not found'));
      console.log('');
      console.log(chalk.dim('  To share via Gist, install GitHub CLI:'));
      console.log(chalk.cyan('  https://cli.github.com'));
      console.log('');
      console.log(chalk.dim('  Or manually create a Gist with the content below:'));
      console.log('');
      printFallbackReport(markdown);
      return;
    }

    // Create the gist using gh CLI
    const filename = `vibe-check-${sanitizeUrl(report.url)}-${Date.now()}.md`;

    // Write temp file and create gist
    const fs = await import('node:fs');
    const path = await import('node:path');
    const os = await import('node:os');

    const tmpFile = path.join(os.tmpdir(), filename);
    fs.writeFileSync(tmpFile, markdown);

    const result = execSync(`gh gist create "${tmpFile}" --public -d "vibe-check report for ${report.url}"`, {
      encoding: 'utf-8',
      timeout: 15000,
    }).trim();

    // Clean up temp file
    try { fs.unlinkSync(tmpFile); } catch {}

    spinner.succeed(chalk.dim('  Gist created!'));
    console.log('');
    console.log(`  ${chalk.bold('Share your vibe report →')} ${chalk.cyan.underline(result)}`);
    console.log('');

  } catch (error) {
    spinner.fail(chalk.dim('  Failed to create Gist'));
    console.log(chalk.dim(`  Error: ${error.message}`));
    console.log('');
    console.log(chalk.dim('  Here\'s the report to manually share:'));
    console.log('');
    printFallbackReport(markdown);
  }
}

function generateMarkdownReport(report) {
  const { url, analyses, verdict, roast, requestCount, timestamp } = report;

  const traitRows = verdict.traits
    .map(t => `| ${t.emoji} ${capitalize(t.name)} | ${renderTextBar(t.score)} | ${t.score}/100 | ${t.label} |`)
    .join('\n');

  const speedStats = analyses.speed.stats;
  const sizeStats = analyses.size.stats;
  const statusCodes = Object.entries(analyses.honesty.stats.statusCodes || {})
    .map(([code, count]) => `${code} (×${count})`)
    .join(', ');

  return `# 🔮 vibe-check report

**Target:** \`${url}\`
**Requests:** ${requestCount} · **Date:** ${new Date(timestamp).toLocaleString()}

---

## ${verdict.emoji} Verdict: **${verdict.label}** — ${verdict.overallScore}/100

> *"${roast}"*

${verdict.tagline}

---

## Trait Breakdown

| Trait | Bar | Score | Label |
|-------|-----|-------|-------|
${traitRows}

---

## Quick Stats

| Metric | Value |
|--------|-------|
| Avg Response Time | ${speedStats.avg}ms |
| P50 | ${speedStats.p50}ms |
| P95 | ${speedStats.p95}ms |
| Avg Payload Size | ${formatBytes(sizeStats.avgSize)} |
| Compressed | ${sizeStats.compressed ? '✓ Yes' : '✗ No'} |
| Status Codes | ${statusCodes} |

---

## Trait Details

${Object.entries(analyses).map(([key, a]) =>
  `### ${a.emoji} ${capitalize(key)}: ${a.label} (${a.score}/100)\n${a.detail}`
).join('\n\n')}

---

<sub>Generated by [vibe-check](https://github.com/ran4om/vibe-check) — Give any API a personality report</sub>
`;
}

function renderTextBar(score) {
  const filled = Math.round((score / 100) * 10);
  const empty = 10 - filled;
  return '█'.repeat(filled) + '░'.repeat(empty);
}

function capitalize(str) {
  return str.charAt(0).toUpperCase() + str.slice(1);
}

function sanitizeUrl(url) {
  return url
    .replace(/https?:\/\//, '')
    .replace(/[^a-zA-Z0-9]/g, '-')
    .replace(/-+/g, '-')
    .slice(0, 40);
}

function printFallbackReport(markdown) {
  const lines = markdown.split('\n');
  for (const line of lines) {
    console.log(chalk.dim(`  ${line}`));
  }
  console.log('');
}
